%YAML:1.0

#common parameters
vins_folder_path: "/home/tony-ws/catkin_ws/src/VINS"
imu_topic: "/imu_3dm_gx4/imu"
image_topic: "/mv_25001498/image_raw"
output_path: "/config/3dm/vins_result.csv"         # vins outputs will be wrttento vins_folder_path + output_path

#camera calibration 
# model_type: PINHOLE
# camera_name: camera
# image_width: 752
# image_height: 480
# distortion_parameters:
#    k1: -2.6961869604347621e-01
#    k2: 6.1399735304865526e-02
#    p1: 1.0982352181142063e-04
#    p2: -1.4746081136421095e-04
# projection_parameters:
#    fx: 3.6315117981348203e+02
#    fy: 3.6306124958499015e+02
#    cx: 3.6861865048713400e+02
#    cy: 2.3794264432569818e+02

# MEI is better than PINHOLE for large FOV camera
model_type: MEI
camera_name: camera
image_width: 752
image_height: 480
mirror_parameters:
   xi: 2.0571188355936370e+00
distortion_parameters:
   k1: 7.1446192804741557e-02
   k2: 5.0589462205471503e-01
   p1: 4.7266856950464269e-05
   p2: -5.4920938472589670e-04
projection_parameters:
   gamma1: 1.1146835125732011e+03
   gamma2: 1.1140831181025417e+03
   u0: 3.6717145806673022e+02
   v0: 2.3849930556972612e+02

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 
ex_calib_result_path: "/config/euroc/ex_calib_result.yaml"  # If you choose 1 or 2, the extrinsic calibration result will be written vins_folder_path + ex_calib_result_path.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0, 0, -1, 
           -1, 0, 0, 
           0, 1, 0]

#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 0, 0, 0.02]

#feature traker paprameters

max_cnt: 150            # max feature number in feature tracking
min_dist: 20            # min distance between two features 
freq: 20                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 0             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points
fisheye_mask_path: "/config/fisheye_mask.jpg" # if using fisheye, this mask will be used.
#optimization parameters

max_solver_time: 0.035  # max solver itration time (ms), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.2          # accelerometer measurement noise standard deviation.
gyr_n: 0.05         # gyroscope measurement noise standard deviation.
acc_w: 0.002        # accelerometer bias random work noise standard deviation.
gyr_w: 4.0e-5       # gyroscope bias random work noise standard deviation.
g_norm: 9.805       #


#loop closure parameters
loop_closure: 0   #if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
                     #also give the camera calibration file same as feature_tracker node
pattern_file: "/support_files/brief_pattern.yml"
voc_file: "/support_files/brief_k10L6.bin"
min_loop_num: 20
